"type: experimental":
  - changed-files:
    - any-glob-to-any-file:
      - 'crates/coxswain-controller/src/gw_types.rs'
      - 'crates/coxswain-controller/Cargo.toml'
      - 'crates/coxswain-bin/Cargo.toml'
      - '.github/workflows/experimental.yml'

"needs: conformance":
  - changed-files:
    - any-glob-to-any-file:
      - 'crates/coxswain-controller/src/gateway_api/**'
      - 'crates/coxswain-controller/src/gw_types.rs'
      - 'crates/coxswain-controller/src/controller/gateway_class_status.rs'
      - 'crates/coxswain-controller/src/controller/gateway_status.rs'
      - 'crates/coxswain-controller/src/controller/conditions.rs'
      - 'crates/coxswain-controller/src/tls.rs'
      - 'conformance/**'
      - 'deploy/manifests/namespace.yaml'
      - 'deploy/manifests/rbac.yaml'
      - 'deploy/manifests/gateway-class.yaml'
      - '.gateway-api-version'
      - '.github/workflows/conformance.yml'
