//! Generated by kopium from the experimental-channel Gateway API CRD at `config/crd/experimental/gateway.networking.x-k8s.io_xbackends.yaml`.
//! Do not edit by hand — regenerate with `cargo run -p xtask -- gateway-api-types`.

// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium --schema=derived --derive=JsonSchema --derive=Default --derive=PartialEq --docs -f -
// kopium version: 0.24.0

#[allow(unused_imports)]
mod prelude {
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use schemars::JsonSchema;
    pub use serde::{Deserialize, Serialize};
}

use self::prelude::*;

/// Spec defines the desired state of XBackend.
#[derive(CustomResource, Serialize, Deserialize, Clone, Debug, JsonSchema, Default, PartialEq)]
#[kube(
    group = "gateway.networking.x-k8s.io",
    version = "v1alpha1",
    kind = "XBackend",
    plural = "xbackends"
)]
#[kube(namespaced)]
#[kube(status = "XBackendStatus")]
#[kube(derive = "Default")]
#[kube(derive = "PartialEq")]
pub struct XBackendSpec {
    /// ExternalHostname specifies the configuration for an ExternalHostname
    /// backend. This field must be set when type is ExternalHostname and must
    /// be unset otherwise.
    ///
    /// Support: Extended
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "externalHostname"
    )]
    pub external_hostname: Option<XBackendExternalHostname>,
    /// Port defines the port that the implementation should use when connecting
    /// to this backend.
    pub port: XBackendPort,
    /// Protocol defines the protocol for backend communication.
    ///
    /// In the common case, the underlying transport protocol for the
    /// proxied traffic will already have been determined and processed
    /// by the dataplane at the routing step. Where this field is useful
    /// is either for higher level protocols or asymmetrical protocol
    /// configurations (e.g. version upgrades or h2c).
    ///
    /// When set, the implementation uses the specified protocol when connecting
    /// to this backend. When not set, the implementation will use the protocol
    /// determined by the route or listener configuration.
    ///
    /// Support: Core - HTTP, HTTP2, H2C, and HTTP11
    ///
    /// Support: Extended - GRPC, MCP, TCP
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub protocol: Option<XBackendProtocol>,
    /// TLS defines the TLS configuration that the implementation should use
    /// when connecting to the backend.
    ///
    /// ExternalHostname backends SHOULD have TLS configured; the lack of TLS
    /// for external hostnames should be considered insecure and a security risk.
    ///
    /// Support: Extended
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tls: Option<XBackendTls>,
    /// Type defines the backend type.
    #[serde(rename = "type")]
    pub r#type: XBackendType,
}

/// ExternalHostname specifies the configuration for an ExternalHostname
/// backend. This field must be set when type is ExternalHostname and must
/// be unset otherwise.
///
/// Support: Extended
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, Default, PartialEq)]
pub struct XBackendExternalHostname {
    /// Hostname specifies the FQDN used to reach this backend.
    /// IP addresses are not allowed in this field.
    pub hostname: String,
}

/// Port defines the port that the implementation should use when connecting
/// to this backend.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, Default, PartialEq)]
pub struct XBackendPort {
    /// Name represents the name of this port. All ports in a Backend must have
    /// a unique name. Name must either be an empty string or pass DNS_LABEL
    /// validation (lowercase alphanumeric or '-', starting and ending with an
    /// alphanumeric character, at most 63 characters).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Port represents the port number of the endpoint.
    pub port: i32,
}

/// Spec defines the desired state of XBackend.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, PartialEq)]
pub enum XBackendProtocol {
    #[serde(rename = "TCP")]
    Tcp,
    #[serde(rename = "HTTP")]
    Http,
    #[serde(rename = "HTTP2")]
    Http2,
    #[serde(rename = "HTTP11")]
    Http11,
    #[serde(rename = "H2C")]
    H2c,
    #[serde(rename = "MCP")]
    Mcp,
}

/// TLS defines the TLS configuration that the implementation should use
/// when connecting to the backend.
///
/// ExternalHostname backends SHOULD have TLS configured; the lack of TLS
/// for external hostnames should be considered insecure and a security risk.
///
/// Support: Extended
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, Default, PartialEq)]
pub struct XBackendTls {
    /// ClientCertificateRef is a reference to a Secret containing the client
    /// TLS certificate and private key for mutual TLS. This field is required
    /// when mode is ClientAndServer and must be unset otherwise.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "clientCertificateRef"
    )]
    pub client_certificate_ref: Option<XBackendTlsClientCertificateRef>,
    /// Mode defines the TLS mode for the backend connection.
    pub mode: XBackendTlsMode,
    /// Validation contains TLS validation configuration for the backend connection.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validation: Option<XBackendTlsValidation>,
}

/// ClientCertificateRef is a reference to a Secret containing the client
/// TLS certificate and private key for mutual TLS. This field is required
/// when mode is ClientAndServer and must be unset otherwise.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, Default, PartialEq)]
pub struct XBackendTlsClientCertificateRef {
    /// Group is the group of the referent. For example, "gateway.networking.k8s.io".
    /// When unspecified or empty string, core API group is inferred.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    /// Kind is kind of the referent. For example "Secret".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// Name is the name of the referent.
    pub name: String,
    /// Namespace is the namespace of the referenced object. When unspecified, the local
    /// namespace is inferred.
    ///
    /// Note that when a namespace different than the local namespace is specified,
    /// a ReferenceGrant object is required in the referent namespace to allow that
    /// namespace's owner to accept the reference. See the ReferenceGrant
    /// documentation for details.
    ///
    /// Support: Core
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

/// TLS defines the TLS configuration that the implementation should use
/// when connecting to the backend.
///
/// ExternalHostname backends SHOULD have TLS configured; the lack of TLS
/// for external hostnames should be considered insecure and a security risk.
///
/// Support: Extended
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, PartialEq)]
pub enum XBackendTlsMode {
    None,
    ServerOnly,
    ClientAndServer,
}

/// Validation contains TLS validation configuration for the backend connection.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, Default, PartialEq)]
pub struct XBackendTlsValidation {
    /// CACertificateRefs contains one or more references to Kubernetes objects that
    /// contain a PEM-encoded TLS CA certificate bundle, which is used to
    /// validate a TLS handshake between the Gateway and backend Pod.
    ///
    /// If CACertificateRefs is empty or unspecified, then WellKnownCACertificates must be
    /// specified. Only one of CACertificateRefs or WellKnownCACertificates may be specified,
    /// not both. If CACertificateRefs is empty or unspecified, the configuration for
    /// WellKnownCACertificates MUST be honored instead if supported by the implementation.
    ///
    /// A CACertificateRef is invalid if:
    ///
    /// * It refers to a resource that cannot be resolved (e.g., the referenced resource
    ///   does not exist) or is misconfigured (e.g., a ConfigMap does not contain a key
    ///   named `ca.crt`). In this case, the Reason must be set to `InvalidCACertificateRef`
    ///   and the Message of the Condition must indicate which reference is invalid and why.
    ///
    /// * It refers to an unknown or unsupported kind of resource. In this case, the Reason
    ///   must be set to `InvalidKind` and the Message of the Condition must explain which
    ///   kind of resource is unknown or unsupported.
    ///
    /// * It refers to a resource in another namespace. This may change in future
    ///   spec updates.
    ///
    /// Implementations MAY choose to perform further validation of the certificate
    /// content (e.g., checking expiry or enforcing specific formats). In such cases,
    /// an implementation-specific Reason and Message must be set for the invalid reference.
    ///
    /// In all cases, the implementation MUST ensure the `ResolvedRefs` Condition on
    /// the BackendTLSPolicy is set to `status: False`, with a Reason and Message
    /// that indicate the cause of the error. Connections using an invalid
    /// CACertificateRef MUST fail, and the client MUST receive an HTTP 5xx error
    /// response. If ALL CACertificateRefs are invalid, the implementation MUST also
    /// ensure the `Accepted` Condition on the BackendTLSPolicy is set to
    /// `status: False`, with a Reason `NoValidCACertificate`.
    ///
    /// A single CACertificateRef to a Kubernetes ConfigMap kind has "Core" support.
    /// Implementations MAY choose to support attaching multiple certificates to
    /// a backend, but this behavior is implementation-specific.
    ///
    /// Support: Core - An optional single reference to a Kubernetes ConfigMap,
    /// with the CA certificate in a key named `ca.crt`.
    ///
    /// Support: Implementation-specific - More than one reference, other kinds
    /// of resources, or a single reference that includes multiple certificates.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "caCertificateRefs"
    )]
    pub ca_certificate_refs: Option<Vec<XBackendTlsValidationCaCertificateRefs>>,
    /// Hostname is used for two purposes in the connection between Gateways and
    /// backends:
    ///
    /// 1. Hostname MUST be used as the SNI to connect to the backend (RFC 6066).
    /// 2. Hostname MUST be used for authentication and MUST match the certificate
    ///    served by the matching backend, unless SubjectAltNames is specified.
    /// 3. If SubjectAltNames are specified, Hostname can be used for certificate selection
    ///    but MUST NOT be used for authentication. If you want to use the value
    ///    of the Hostname field for authentication, you MUST add it to the SubjectAltNames list.
    ///
    /// Support: Core
    pub hostname: String,
    /// SubjectAltNames contains one or more Subject Alternative Names.
    /// When specified the certificate served from the backend MUST
    /// have at least one Subject Alternate Name matching one of the specified SubjectAltNames.
    ///
    /// Support: Extended
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "subjectAltNames"
    )]
    pub subject_alt_names: Option<Vec<XBackendTlsValidationSubjectAltNames>>,
    /// WellKnownCACertificates specifies whether a well-known set of CA certificates
    /// may be used in the TLS handshake between the gateway and backend pod.
    ///
    /// If WellKnownCACertificates is unspecified or empty (""), then CACertificateRefs
    /// must be specified with at least one entry for a valid configuration. Only one of
    /// CACertificateRefs or WellKnownCACertificates may be specified, not both.
    /// If an implementation does not support the WellKnownCACertificates field, or
    /// the supplied value is not recognized, the implementation MUST ensure the
    /// `Accepted` Condition on the BackendTLSPolicy is set to `status: False`, with
    /// a Reason `Invalid`.
    ///
    /// Valid values include:
    /// * "System" - indicates that well-known system CA certificates should be used.
    ///
    /// Implementations MAY define their own sets of CA certificates. Such definitions
    /// MUST use an implementation-specific, prefixed name, such as
    /// `mycompany.com/my-custom-ca-certificates`.
    ///
    /// Support: Implementation-specific
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "wellKnownCACertificates"
    )]
    pub well_known_ca_certificates: Option<String>,
}

/// LocalObjectReference identifies an API object within the namespace of the
/// referrer.
/// The API object must be valid in the cluster; the Group and Kind must
/// be registered in the cluster for this reference to be valid.
///
/// References to objects with invalid Group and Kind are not valid, and must
/// be rejected by the implementation, with appropriate Conditions set
/// on the containing object.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, Default, PartialEq)]
pub struct XBackendTlsValidationCaCertificateRefs {
    /// Group is the group of the referent. For example, "gateway.networking.k8s.io".
    /// When unspecified or empty string, core API group is inferred.
    pub group: String,
    /// Kind is kind of the referent. For example "HTTPRoute" or "Service".
    pub kind: String,
    /// Name is the name of the referent.
    pub name: String,
}

/// SubjectAltName represents Subject Alternative Name.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, Default, PartialEq)]
pub struct XBackendTlsValidationSubjectAltNames {
    /// Hostname contains Subject Alternative Name specified in DNS name format.
    /// Required when Type is set to Hostname, ignored otherwise.
    ///
    /// Support: Core
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    /// Type determines the format of the Subject Alternative Name. Always required.
    ///
    /// Support: Core
    #[serde(rename = "type")]
    pub r#type: XBackendTlsValidationSubjectAltNamesType,
    /// URI contains Subject Alternative Name specified in a full URI format.
    /// It MUST include both a scheme (e.g., "http" or "ftp") and a scheme-specific-part.
    /// Common values include SPIFFE IDs like "spiffe://mycluster.example.com/ns/myns/sa/svc1sa".
    /// Required when Type is set to URI, ignored otherwise.
    ///
    /// Support: Core
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
}

/// SubjectAltName represents Subject Alternative Name.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, PartialEq)]
pub enum XBackendTlsValidationSubjectAltNamesType {
    Hostname,
    #[serde(rename = "URI")]
    Uri,
}

/// Spec defines the desired state of XBackend.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, PartialEq)]
pub enum XBackendType {
    ExternalHostname,
}

/// Status defines the current state of XBackend.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, Default, PartialEq)]
pub struct XBackendStatus {
    /// Ancestors is a list of parent resources associated with this Backend,
    /// and the status of the Backend with respect to each parent.
    ///
    /// A maximum of 32 parents will be represented in this list. An empty list
    /// indicates that the Backend is not associated with any parents.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parents: Option<Vec<XBackendStatusParents>>,
}

/// BackendAncestorStatus describes the status of a Backend with respect to a
/// specific parent resource (typically a Gateway).
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, Default, PartialEq)]
pub struct XBackendStatusParents {
    /// For Kubernetes API conventions, see:
    /// <https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties>
    /// conditions represent the current state of the Backend resource.
    /// Each condition has a unique type and reflects the status of a specific aspect of the resource.
    ///
    /// Defined condition types include:
    /// - "Accepted": the resource has been acknowledged and accepteed by the controller
    ///
    /// The status of each condition is one of True, False, or Unknown.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    /// ControllerName is a domain/path string that indicates the name of the
    /// controller that manages the Backend.
    ///
    /// Example: "example.net/gateway-controller".
    ///
    /// The format of this field is DOMAIN "/" PATH, where DOMAIN and PATH are
    /// valid Kubernetes names
    /// (<https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).>
    #[serde(rename = "controllerName")]
    pub controller_name: String,
    /// AncestorRef identifies the parent resource that this status is associated with.
    #[serde(rename = "parentRef")]
    pub parent_ref: XBackendStatusParentsParentRef,
}

/// AncestorRef identifies the parent resource that this status is associated with.
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, Default, PartialEq)]
pub struct XBackendStatusParentsParentRef {
    /// Group is the group of the referent.
    /// When unspecified, "gateway.networking.k8s.io" is inferred.
    /// To set the core API group (such as for a "Service" kind referent),
    /// Group must be explicitly set to "" (empty string).
    ///
    /// Support: Core
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    /// Kind is kind of the referent.
    ///
    /// There are two kinds of parent resources with "Core" support:
    ///
    /// * Gateway (Gateway conformance profile)
    /// * Service (Mesh conformance profile, ClusterIP Services only)
    ///
    /// Support for other resources is Implementation-Specific.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// Name is the name of the referent.
    ///
    /// Support: Core
    pub name: String,
    /// Namespace is the namespace of the referent. When unspecified, this refers
    /// to the local namespace of the Route.
    ///
    /// Note that there are specific rules for ParentRefs which cross namespace
    /// boundaries. Cross-namespace references are only valid if they are explicitly
    /// allowed by something in the namespace they are referring to. For example:
    /// Gateway has the AllowedRoutes field, and ReferenceGrant provides a
    /// generic way to enable any other kind of cross-namespace reference.
    ///
    ///
    /// ParentRefs from a Route to a Service in the same namespace are "producer"
    /// routes, which apply default routing rules to inbound connections from
    /// any namespace to the Service.
    ///
    /// ParentRefs from a Route to a Service in a different namespace are
    /// "consumer" routes, and these routing rules are only applied to outbound
    /// connections originating from the same namespace as the Route, for which
    /// the intended destination of the connections are a Service targeted as a
    /// ParentRef of the Route.
    ///
    ///
    /// Support: Core
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// Port is the network port this Route targets. It can be interpreted
    /// differently based on the type of parent resource.
    ///
    /// When the parent resource is a Gateway, this targets all listeners
    /// listening on the specified port that also support this kind of Route(and
    /// select this Route). It's not recommended to set `Port` unless the
    /// networking behaviors specified in a Route must apply to a specific port
    /// as opposed to a listener(s) whose port(s) may be changed. When both Port
    /// and SectionName are specified, the name and port of the selected listener
    /// must match both specified values.
    ///
    ///
    /// When the parent resource is a Service, this targets a specific port in the
    /// Service spec. When both Port (experimental) and SectionName are specified,
    /// the name and port of the selected port must match both specified values.
    ///
    ///
    /// Implementations MAY choose to support other parent resources.
    /// Implementations supporting other types of parent resources MUST clearly
    /// document how/if Port is interpreted.
    ///
    /// For the purpose of status, an attachment is considered successful as
    /// long as the parent resource accepts it partially. For example, Gateway
    /// listeners can restrict which Routes can attach to them by Route kind,
    /// namespace, or hostname. If 1 of 2 Gateway listeners accept attachment
    /// from the referencing Route, the Route MUST be considered successfully
    /// attached. If no Gateway listeners accept attachment from this Route,
    /// the Route MUST be considered detached from the Gateway.
    ///
    /// Support: Extended
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// SectionName is the name of a section within the target resource. In the
    /// following resources, SectionName is interpreted as the following:
    ///
    /// * Gateway: Listener name. When both Port (experimental) and SectionName
    /// are specified, the name and port of the selected listener must match
    /// both specified values.
    /// * Service: Port name. When both Port (experimental) and SectionName
    /// are specified, the name and port of the selected listener must match
    /// both specified values.
    ///
    /// Implementations MAY choose to support attaching Routes to other resources.
    /// If that is the case, they MUST clearly document how SectionName is
    /// interpreted.
    ///
    /// When unspecified (empty string), this will reference the entire resource.
    /// For the purpose of status, an attachment is considered successful if at
    /// least one section in the parent resource accepts it. For example, Gateway
    /// listeners can restrict which Routes can attach to them by Route kind,
    /// namespace, or hostname. If 1 of 2 Gateway listeners accept attachment from
    /// the referencing Route, the Route MUST be considered successfully
    /// attached. If no Gateway listeners accept attachment from this Route, the
    /// Route MUST be considered detached from the Gateway.
    ///
    /// Support: Core
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "sectionName"
    )]
    pub section_name: Option<String>,
}

impl Default for XBackendProtocol {
    fn default() -> Self {
        XBackendProtocol::Tcp
    }
}

impl Default for XBackendTlsMode {
    fn default() -> Self {
        XBackendTlsMode::None
    }
}

impl Default for XBackendTlsValidationSubjectAltNamesType {
    fn default() -> Self {
        XBackendTlsValidationSubjectAltNamesType::Hostname
    }
}

impl Default for XBackendType {
    fn default() -> Self {
        XBackendType::ExternalHostname
    }
}
