{{- if and .Values.controller.enabled .Values.controller.podDisruptionBudget.enabled (ge (int .Values.controller.replicas) 2) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "coxswain.controller.fullname" . }}
  namespace: {{ include "coxswain.namespace" . }}
  labels:
    {{- include "coxswain.controller.selectorLabels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.controller.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "coxswain.controller.selectorLabels" . | nindent 6 }}
{{- end }}
