{{- if .Values.ingressClass.create -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingressClass.name }}
  labels:
    {{- include "coxswain.labels" . | nindent 4 }}
spec:
  # Must match controllerName (COXSWAIN_CONTROLLER_NAME) in the Deployment.
  controller: {{ .Values.controllerName }}
{{- end }}
