apiVersion: v1
kind: Service
metadata:
  name: {{ include "coxswain.fullname" . }}-internal
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "coxswain.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  {{- with .Values.service.internal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "coxswain.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  ports:
    - name: health
      port: {{ .Values.health.port }}
      targetPort: health
      protocol: TCP
    - name: admin
      port: {{ .Values.admin.port }}
      targetPort: admin
      protocol: TCP
