{{- if and .Values.proxy.shared.enabled .Values.proxy.shared.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "coxswain.sharedProxy.fullname" . }}
  namespace: {{ include "coxswain.namespace" . }}
  labels:
    {{- include "coxswain.sharedProxy.selectorLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "coxswain.sharedProxy.fullname" . }}
  minReplicas: {{ .Values.proxy.shared.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.proxy.shared.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.proxy.shared.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
