{{- $autoscalingEnabled := .Values.proxy.shared.autoscaling.enabled -}}
{{- $floor := ternary (int .Values.proxy.shared.autoscaling.minReplicas) (int .Values.proxy.shared.replicas) $autoscalingEnabled -}}
{{- if and .Values.proxy.shared.enabled .Values.proxy.shared.podDisruptionBudget.enabled (ge $floor 2) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "coxswain.sharedProxy.fullname" . }}
  namespace: {{ include "coxswain.namespace" . }}
  labels:
    {{- include "coxswain.sharedProxy.selectorLabels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.proxy.shared.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "coxswain.sharedProxy.selectorLabels" . | nindent 6 }}
{{- end }}
