apiVersion: gateway.networking.k8s.io/v1
date: "2026-06-03T12:08:57+01:00"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.5.1
implementation:
  contact:
  - ""
  organization: coxswain-labs
  project: coxswain
  url: https://github.com/coxswain-labs/coxswain
  version: 79c95b3
kind: ConformanceReport
mode: default
profiles:
- core:
    failedTests:
    - HTTPRouteWeight
    result: failure
    statistics:
      Failed: 1
      Passed: 32
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 2
      Skipped: 0
    supportedFeatures:
    - HTTPRouteMethodMatching
    - HTTPRouteQueryParamMatching
    unsupportedFeatures:
    - BackendTLSPolicy
    - BackendTLSPolicySANValidation
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - GatewayStaticAddresses
    - HTTPRoute303RedirectStatusCode
    - HTTPRoute307RedirectStatusCode
    - HTTPRoute308RedirectStatusCode
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteBackendTimeout
    - HTTPRouteCORS
    - HTTPRouteDestinationPortMatching
    - HTTPRouteHostRewrite
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
    - ListenerSet
  name: GATEWAY-HTTP
  summary: Core tests failed with 1 test failures. Extended tests succeeded.
