//! Self-signed certificate generation for TLS e2e tests.

use base64::Engine as _;
use rcgen::{
    BasicConstraints, CertificateParams, ExtendedKeyUsagePurpose, IsCa, Issuer, KeyPair,
    KeyUsagePurpose,
};

/// A self-signed certificate generated by `rcgen` for use in e2e tests.
pub struct GeneratedCert {
    /// PEM-encoded self-signed certificate.
    pub cert_pem: String,
    /// PEM-encoded private key.
    pub key_pem: String,
    /// Hostname the certificate was issued for.
    pub host: String,
}

impl GeneratedCert {
    /// Generate a self-signed certificate valid for `host`.
    pub fn for_host(host: &str) -> Self {
        let certified = rcgen::generate_simple_self_signed(vec![host.to_string()])
            .unwrap_or_else(|e| panic!("rcgen self-signed cert for {host}: {e}"));
        Self {
            cert_pem: certified.cert.pem(),
            key_pem: certified.signing_key.serialize_pem(),
            host: host.to_string(),
        }
    }

    /// Generate a self-signed certificate valid for every entry in `hosts`.
    /// Used when one backend pod must satisfy verification by multiple distinct
    /// SNI hostnames (e.g. the BackendTLSPolicy section-name routing test).
    pub fn for_hosts(hosts: &[&str]) -> Self {
        let owned: Vec<String> = hosts.iter().map(|h| (*h).to_string()).collect();
        let certified = rcgen::generate_simple_self_signed(owned)
            .unwrap_or_else(|e| panic!("rcgen self-signed cert for {hosts:?}: {e}"));
        Self {
            cert_pem: certified.cert.pem(),
            key_pem: certified.signing_key.serialize_pem(),
            host: hosts.first().map(|h| (*h).to_string()).unwrap_or_default(),
        }
    }

    /// PEM cert encoded as base64 for use in a Kubernetes Secret's `data` field.
    pub fn cert_b64(&self) -> String {
        base64::engine::general_purpose::STANDARD.encode(self.cert_pem.as_bytes())
    }

    /// PEM key encoded as base64 for use in a Kubernetes Secret's `data` field.
    pub fn key_b64(&self) -> String {
        base64::engine::general_purpose::STANDARD.encode(self.key_pem.as_bytes())
    }

    /// PEM cert with all continuation lines indented by `spaces` spaces, suitable for embedding
    /// in a YAML `|` block scalar whose placeholder already carries the first-line indentation.
    pub fn cert_pem_indented(&self, spaces: usize) -> String {
        let indent = " ".repeat(spaces);
        self.cert_pem
            .lines()
            .collect::<Vec<_>>()
            .join(&format!("\n{indent}"))
    }
}

/// A CA certificate + a leaf certificate signed by that CA, for mTLS e2e tests.
///
/// The CA cert goes into the `ca.crt` field of a Secret labeled
/// `ingress.coxswain-labs.dev/auth-tls=true`.  The leaf cert + key are
/// presented as the client identity in the TLS handshake.
pub struct MtlsCerts {
    /// PEM-encoded CA certificate (for the `ca.crt` key in the Kubernetes Secret).
    pub ca_cert_pem: String,
    /// PEM-encoded client leaf certificate (presented during the TLS handshake).
    pub client_cert_pem: String,
    /// PEM-encoded client private key (paired with `client_cert_pem`).
    pub client_key_pem: String,
}

impl MtlsCerts {
    /// Generate a fresh CA + a client leaf certificate signed by that CA.
    ///
    /// The leaf carries `ExtendedKeyUsage: clientAuth` so BoringSSL and
    /// rustls both accept it as a valid client certificate.
    #[must_use]
    pub fn generate() -> Self {
        // ── CA certificate ───────────────────────────────────────────────────
        let mut ca_params =
            CertificateParams::new(vec![]).unwrap_or_else(|e| panic!("rcgen CA params: {e}"));
        ca_params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
        ca_params.key_usages = vec![
            KeyUsagePurpose::DigitalSignature,
            KeyUsagePurpose::KeyCertSign,
            KeyUsagePurpose::CrlSign,
        ];
        let ca_key = KeyPair::generate().unwrap_or_else(|e| panic!("rcgen CA key: {e}"));
        let ca_cert = ca_params
            .self_signed(&ca_key)
            .unwrap_or_else(|e| panic!("rcgen CA self-sign: {e}"));
        let ca_issuer = Issuer::new(ca_params, ca_key);

        // ── Client leaf certificate signed by the CA ─────────────────────────
        let mut leaf_params = CertificateParams::new(vec!["mtls-client".to_string()])
            .unwrap_or_else(|e| panic!("rcgen leaf params: {e}"));
        leaf_params.key_usages = vec![KeyUsagePurpose::DigitalSignature];
        leaf_params.extended_key_usages = vec![ExtendedKeyUsagePurpose::ClientAuth];
        let leaf_key = KeyPair::generate().unwrap_or_else(|e| panic!("rcgen leaf key: {e}"));
        let leaf_cert = leaf_params
            .signed_by(&leaf_key, &ca_issuer)
            .unwrap_or_else(|e| panic!("rcgen leaf CA-sign: {e}"));

        Self {
            ca_cert_pem: ca_cert.pem(),
            client_cert_pem: leaf_cert.pem(),
            client_key_pem: leaf_key.serialize_pem(),
        }
    }

    /// CA certificate PEM encoded as base64, for use in a Kubernetes Secret's `data` field.
    #[must_use]
    pub fn ca_cert_b64(&self) -> String {
        base64::engine::general_purpose::STANDARD.encode(self.ca_cert_pem.as_bytes())
    }
}
