use base64::Engine as _;

/// A self-signed certificate generated by `rcgen` for use in e2e tests.
pub struct GeneratedCert {
    pub cert_pem: String,
    pub key_pem: String,
    pub host: String,
}

impl GeneratedCert {
    pub fn for_host(host: &str) -> Self {
        let certified = rcgen::generate_simple_self_signed(vec![host.to_string()])
            .expect("rcgen self-signed cert");
        Self {
            cert_pem: certified.cert.pem(),
            key_pem: certified.key_pair.serialize_pem(),
            host: host.to_string(),
        }
    }

    /// PEM cert encoded as base64 for use in a Kubernetes Secret's `data` field.
    pub fn cert_b64(&self) -> String {
        base64::engine::general_purpose::STANDARD.encode(self.cert_pem.as_bytes())
    }

    /// PEM key encoded as base64 for use in a Kubernetes Secret's `data` field.
    pub fn key_b64(&self) -> String {
        base64::engine::general_purpose::STANDARD.encode(self.key_pem.as_bytes())
    }
}
