#!/usr/bin/env bash
# Validate CRD manifests with `kubeconform` (#515, superseding the "Cargo /
# CRD" checklist item of #503).
#
# Two independent sets, both exercised:
#
# 1. Coxswain's own 10 CRDs (`deploy/manifests/crds/*.yaml`, generated by
#    `crates/coxswain-core/examples/crdgen.rs`). `charts/coxswain/crds/*.yaml`
#    is a byte-identical copy — enforced by the
#    `crd::*::chart_crd_is_byte_identical_to_manifest_crd` snapshot tests in
#    coxswain-core — so validating one set covers both.
# 2. The upstream Gateway API CRDs at the current supported version, fetched
#    live the same way `scripts/setup-conformance.sh` and DEVELOPMENT.md's
#    local-controller setup already do. This is the literal regression guard
#    for kubernetes-sigs/gateway-api#4402 ("Standard CRD manifests contain
#    invalid `null` values in `.status` fields, breaking schema validation" —
#    fixed upstream in v1.6 by gateway-api#4712, "generator: omit top-level CRD
#    status from manifests"). Coxswain vendors none of these CRDs (installed
#    from the release URL, never committed to this repo — see DEVELOPMENT.md),
#    so there is nothing to "regenerate" on our side; this check is what makes
#    "kubeconform passes" a durable claim instead of a one-time observation
#    that would silently go stale on the next Gateway API version bump.
#
# kubeconform's bundled `master-standalone(-strict)` schema catalog has no
# top-level `customresourcedefinition-*.json` file (only its subcomponents —
# confirmed by hand against yannh/kubernetes-json-schema), so this uses the
# same non-standalone schema-location the upstream issue's own repro command
# uses: `.../kubernetes-json-schema/master/{{.NormalizedKubernetesVersion}}/{{.ResourceKind}}.json`.
#
# Downloads a pinned, checksum-verified `kubeconform` release binary into
# `target/tools/` (same trust model as the `@sha256:`-pinned e2e fixture
# images: a fixed version + a verified digest, never a floating tag) rather
# than requiring a pre-installed tool, so this runs identically in CI and for
# any contributor.
#
# Run from the repo root. Exits non-zero on any invalid manifest.

set -euo pipefail

KUBECONFORM_VERSION="0.8.0"
TOOLS_DIR="target/tools"
BIN="${TOOLS_DIR}/kubeconform-${KUBECONFORM_VERSION}"
SCHEMA_LOCATION='https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{.NormalizedKubernetesVersion}}/{{.ResourceKind}}.json'

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch="$(uname -m)"
case "$arch" in
  x86_64) arch="amd64" ;;
  aarch64|arm64) arch="arm64" ;;
  *)
    echo "error: unsupported architecture '$arch' for kubeconform download" >&2
    exit 1
    ;;
esac

# Plain case statement, not an associative array: the default `/bin/bash` on
# macOS is 3.2 (GPLv2-era, last free BSD-licensed release) and has no
# `declare -A` — this script must run unmodified in both a contributor's local
# shell and CI's bash.
platform="${os}-${arch}"
case "$platform" in
  darwin-amd64) checksum="71dbc87ac9f24099a62b93570e65aa06312ba6ac8aea63b7f86e9d999edf5a92" ;;
  darwin-arm64) checksum="f84f4dfbebf4a6b0b230385fa065a39ea35e02608c2b50d025dcf64775a69d67" ;;
  linux-amd64) checksum="9bc2bffbf71f261128533edaf912153948b7ff238f9a531ae6d34466ec287883" ;;
  linux-arm64) checksum="1f53fc8e81258197a35e8603054162a5af1de8c5af13746c71ab680d9534ed87" ;;
  *)
    echo "error: no pinned kubeconform checksum for platform '$platform'" >&2
    exit 1
    ;;
esac

if [ ! -x "$BIN" ]; then
  mkdir -p "$TOOLS_DIR"
  tarball="$(mktemp -d)/kubeconform.tar.gz"
  url="https://github.com/yannh/kubeconform/releases/download/v${KUBECONFORM_VERSION}/kubeconform-${platform}.tar.gz"
  echo ">>> downloading kubeconform v${KUBECONFORM_VERSION} for ${platform}"
  curl -sSfL "$url" -o "$tarball"

  actual="$(shasum -a 256 "$tarball" | awk '{print $1}')"
  if [ "$actual" != "$checksum" ]; then
    echo "error: kubeconform download checksum mismatch" >&2
    echo "  expected: $checksum" >&2
    echo "  actual:   $actual" >&2
    exit 1
  fi

  extract_dir="$(mktemp -d)"
  tar -xzf "$tarball" -C "$extract_dir" kubeconform
  mv "$extract_dir/kubeconform" "$BIN"
  chmod +x "$BIN"
fi

mkdir -p target/tools/kubeconform-schema-cache
run_kubeconform() {
  "$BIN" -strict -summary -cache target/tools/kubeconform-schema-cache -schema-location "$SCHEMA_LOCATION" "$@"
}

status=0

echo ">>> validating deploy/manifests/crds/*.yaml with kubeconform"
if ! run_kubeconform deploy/manifests/crds/*.yaml; then
  echo "FAIL: a coxswain-authored CRD manifest is structurally invalid." >&2
  echo "Regenerate with 'cargo run -p coxswain-core --example crdgen -- <Kind>' per" >&2
  echo "the doc comment in crates/coxswain-core/examples/crdgen.rs, then re-run this check." >&2
  status=1
fi

gateway_api_version="$(scripts/gateway-api-versions.sh --latest)"
gateway_install_yaml="$(mktemp -d)/standard-install.yaml"
gateway_install_url="https://github.com/kubernetes-sigs/gateway-api/releases/download/${gateway_api_version}/standard-install.yaml"
echo ">>> fetching upstream Gateway API CRDs at ${gateway_api_version}"
curl -sSfL "$gateway_install_url" -o "$gateway_install_yaml"

echo ">>> validating upstream Gateway API CRDs (${gateway_api_version}) with kubeconform"
if ! run_kubeconform "$gateway_install_yaml"; then
  echo "FAIL: the upstream Gateway API CRDs at ${gateway_api_version} are structurally" >&2
  echo "invalid (e.g. kubernetes-sigs/gateway-api#4402's null .status fields regressed)." >&2
  echo "This is not coxswain's manifest — report/track upstream and re-pin .gateway-api-versions.json." >&2
  status=1
fi

if [ "$status" -ne 0 ]; then
  exit 1
fi

echo "OK: coxswain's own CRDs and the pinned upstream Gateway API CRDs both pass kubeconform -strict."
