#!/usr/bin/env bash
# Render deploy/manifests/coxswain.yaml FROM the Helm chart.
#
# The chart (charts/coxswain) is the single source of truth for every runtime
# manifest. The raw-manifest / Kustomize install path must produce the *same*
# result as `helm install`, so its non-CRD resources are generated here rather
# than hand-maintained — this is what closes the class of drift where the base
# silently lost resources the chart had (e.g. the controller discovery Service).
#
# CRDs are deliberately excluded: they live in deploy/manifests/crds/ (generated
# by crdgen and validated by scripts/check-crd-kubeconform.sh) and are referenced
# from the Kustomization directly.
#
# Two capabilities the offline `helm template` cannot detect are forced on so the
# rendered output matches a real cluster install: the ValidatingAdmissionPolicy
# API (capability-gated in the chart) via --api-versions, and PodMonitor left off
# because it requires the Prometheus Operator CRDs the base does not assume.
#
# Regenerate after any chart change; scripts/check-manifests-synced.sh fails CI
# on drift.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-$repo_root/deploy/manifests/coxswain.yaml}"

{
  echo "# GENERATED by scripts/render-manifests.sh from charts/coxswain — do not edit."
  echo "# Regenerate after chart changes; scripts/check-manifests-synced.sh gates drift."
  helm template coxswain "$repo_root/charts/coxswain" \
    --namespace coxswain-system \
    --set podMonitor.enabled=false \
    --api-versions 'admissionregistration.k8s.io/v1/ValidatingAdmissionPolicy' \
    --api-versions 'admissionregistration.k8s.io/v1/ValidatingAdmissionPolicyBinding' \
  | sed -e '/^ *helm\.sh\/chart:/d' \
        -e '/^ *app\.kubernetes\.io\/managed-by: *Helm$/d' \
        -e '/^ *app\.kubernetes\.io\/version:/d'
} > "$out"

echo ">>> rendered $out"
