on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

name: Label

jobs:
  apply-labels:
    name: apply-labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - name: Apply labels based on changed files
        uses: actions/labeler@v6
        with:
          configuration-path: .github/labeler.yml
