on:
  schedule:
    - cron: "0 3 * * *"

name: Security audit

jobs:
  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust-with-cache
        with:
          cache-key-prefix: security-audit
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      - run: cargo audit
